/*
	config/user.h
	Defines for userspace configuration
*/

#ifndef __CONFIG_USER__H__
#define __CONFIG_USER__H__

//Name Server
#define CONFIG_NAMESRV_MAX_NAME_ENTRIES 200
#define CONFIG_NAMESRV_TID 1

//Clock Server
#define CONFIG_CLK_MAX_DELAYED_TASKS 50
#define CONFIG_CLK_NUM_COURIERS 5

//Terminal Print Server
#define CONFIG_TERM_SERVER_OUT_BUFFER_SIZE 2048
#define CONFIG_TERM_SERVER_OUT_NUM_COURIERS 5

#define CONFIG_TERM_SERVER_IN_BUFFER_SIZE 2048
#define CONFIG_TERM_SERVER_IN_NUM_COURIERS 1
#define CONFIG_TERM_SERVER_IN_MAX_WAITING_GETC 15

//COM1 Print Server
#define CONFIG_UART1_SERVER_OUT_BUFFER_SIZE 2048
#define CONFIG_UART1_SERVER_OUT_NUM_COURIERS 1

#define CONFIG_UART1_SERVER_IN_BUFFER_SIZE 2048
#define CONFIG_UART1_SERVER_IN_NUM_COURIERS 10
#define CONFIG_UART1_SERVER_IN_MAX_WAITING_GETC 15

//Command Line
#define CONFIG_CLI_MAX_CHARACTERS 50

//Sensor Interpreter
#define CONFIG_SENSOR_INTERPRETER_NUM_COURIERS 1
#define CONFIG_SENSOR_INTERPRETER_MAX_REQUESTS 10

//Route library
#define CONFIG_MAX_ROUTE_SIZE TRACK_MAX
#define CONFIG_MAX_SECONDARY_ROUTE_SIZE 10
#define CONFIG_MAX_NUM_SECONDARY_ROUTES CONFIG_NUM_SWITCHES
#define CONFIG_SECONDARY_ROUTE_LENGTH 600
#define CONFIG_REVERSE_DISTANCE_COST 400
#define CONFIG_RESERVED_EDGE_COST 18000

//Route server
#define CONFIG_MAX_TRAINS 5

//Trains
#define CONFIG_TRAIN_ACCEL_FUDGE_TIME 100
#define CONFIG_TRAIN_REVERSE_STOPPED_DELAY 200
#define CONFIG_TRAIN_COMMAND_DELAY 5
#define CONFIG_TRAIN_MESSAGE_BUFFER_LENGTH 500
#define CONFIG_TRAIN_SENSOR_ATRIBUTION_DELTA 240
#define CONFIG_TRAIN_SAFE_SWITCH_DISTANCE 100
#define CONFIG_TRAIN_REQUESTED_ROUTE_LENGTH 600
#define CONFIG_TRAIN_NOTIFY_POSITION_INTERVAL 3
#define CONFIG_TRAIN_DEST_STOP_WINDOW 5
#define CONFIG_TRAIN_DEST_ARRIVE_WINDOW 200
#define CONFIG_TRAIN_SAFE_STOP_BUFFER 50
#define CONFIG_SLEEP_WORKER_START_DIST 100
#define CONFIG_ROUTE_SERVER_DEBUG_TRAIN 9000
#define CONFIG_TRAIN_SAFE_MERGE_STOP_DISTANCE 250
#define CONFIG_TRAIN_SAFE_REVERSE_BUFFER 350
#define CONFIG_TRAIN_MAX_LENGTH_FROM_PICKUP 200
#define CONFIG_TRAIN_DEADLOCK_DELAY 800

//UI
#define CONFIG_UI_RESERVATION_REFRESH_RATE 25
#endif

