/*
	common/priority.h
	Define number of priorities and
	common names for specific priorities
*/

#ifndef __COMMON_PRIORITY__H__
#define __COMMON_PRIORITY__H__

//number of priority queues
#define PRIORITY_NUM_PRIORITIES 32

//Highest priority group, event handlers, notifiers
#define PRIORITY_EVENT_HANDLER_0 31
#define PRIORITY_EVENT_HANDLER_1 30
#define PRIORITY_EVENT_HANDLER_2 29

//COURIERS
#define PRIORTIY_COURIER_HIGH_0 28
#define PRIORTIY_COURIER_HIGH_1 27

//Important Servers
#define PRIORITY_HIGH_0 26
#define PRIORITY_HIGH_1 25
#define PRIORITY_HIGH_2 24
#define PRIORITY_HIGH_3 23
#define PRIORITY_HIGH_4 22
#define PRIORITY_HIGH_5 21

//Normal Tasks
#define PRIORITY_NORM_0 16
#define PRIORITY_NORM_1 15
#define PRIORITY_NORM_2 14
#define PRIORITY_NORM_3 13
#define PRIORITY_NORM_4 12
#define PRIORITY_NORM_5 11
#define PRIORITY_NORM_6 11

//Low Priority Tasks
#define PRIORITY_LOW_0 7
#define PRIORITY_LOW_1 6
#define PRIORITY_LOW_2 5
#define PRIORITY_LOW_3 4
#define PRIORITY_LOW_4 3
#define PRIORITY_LOW_5 2

//Idle Tasks
#define PRIORITY_IDLE 0
#define PRIORITY_IDLE_HIGH 1

//Define Priorities of specific tasks
#define PRIORITY_SYSTEM_FIRST PRIORITY_LOW_0

#define PRIORITY_NAME_SERVER PRIORITY_HIGH_1

#define PRIORITY_CLOCK_SERVER PRIORITY_HIGH_0
#define PRIORITY_CLOCK_NOTIFIER PRIORITY_EVENT_HANDLER_0

#define PRIORITY_TERM_OUT_SERVER PRIORITY_HIGH_2
#define PRIORITY_TERM_OUT_NOTIFIER PRIORITY_EVENT_HANDLER_2
#define PRIORITY_TERM_IN_SERVER PRIORITY_HIGH_2
#define PRIORITY_TERM_IN_NOTIFIER PRIORITY_EVENT_HANDLER_1

#define PRIORITY_TRAIN_OUT_SERVER PRIORITY_HIGH_2
#define PRIORITY_TRAIN_OUT_NOTIFIER PRIORITY_EVENT_HANDLER_2
#define PRIORITY_TRAIN_IN_SERVER PRIORITY_HIGH_2
#define PRIORITY_TRAIN_IN_NOTIFIER PRIORITY_EVENT_HANDLER_1

#define PRIORITY_MDI_SERVER PRIORITY_HIGH_3
#define PRIORITY_SENSOR_SERVER PRIORITY_HIGH_4
#define PRIORITY_SENSOR_POLLER PRIORITY_HIGH_3
#define PRIORITY_SWITCH_SERVER PRIORITY_HIGH_4
#define PRIORITY_SENSOR_INTERPRETER PRIORITY_HIGH_4

#define PRIORITY_DELAY_WORKER PRIORTIY_COURIER_HIGH_0

#define PRIORITY_USER_TRAIN_COMMAND_DISPATCHER PRIORITY_HIGH_5

#define PRIORITY_USER_CLOCK PRIORITY_HIGH_5
#define PRIORITY_USER_CLI PRIORITY_LOW_0
#define PRIORITY_USER_DRAW_UI PRIORITY_NORM_0

#define PRIORITY_USER_ROUTE_SERVER PRIORITY_NORM_1
//PRIORITY_NORM_1

#define PRIORITY_USER_TRAIN PRIORITY_NORM_0

#define PRIORITY_USER_TRAIN_DISPLAY_TAB PRIORITY_NORM_3
#define PRIORITY_USER_RESERVATION_DISPLAY_TAB PRIORITY_NORM_3
#define PRIORITY_USER_DISPLAY_TABBER PRIORITY_NORM_2

#define PRIORITY_TEST_ZOMB PRIORITY_LOW_4
#define PRIORITY_TEST_ZOMB_SUB PRIORITY_LOW_3


//GAME TASKS PRIORITIES
#define PRIORITY_GAME_TAB PRIORITY_NORM_3
#define PRIORITY_GAME_KEYBOARD PRIORITY_LOW_0
#define PRIORITY_GAME_AI PRIORITY_LOW_1

#endif

